name: SRP

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  runtests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Opera
        run: |
          sudo add-apt-repository 'deb https://deb.opera.com/opera-stable/ stable non-free'
          wget -qO- https://deb.opera.com/archive.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y opera-stable

      - name: Download OperaDriver
        run: |
          wget -N https://github.com/operasoftware/operachromiumdriver/releases/latest/download/operadriver_linux64.zip
          unzip operadriver_linux64.zip
          sudo mv operadriver_linux64/operadriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/operadriver

      - name: Set up Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: |
          mvn test
