name: SRP

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  runtests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Microsoft Edge
        run: |
          wget https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Download EdgeDriver
        run: |
          EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          wget -N https://msedgedriver.azureedge.net/$EDGE_VERSION/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/msedgedriver

      - name: Set up Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: |
          mvn test
